config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :users
  post '/login', to:"index#login"
  get '/login', to: "index#login"
  post '/register', to: "index#register"
  get '/register', to: "index#register"
  get 'index/index', to: "index#index"
  get '/about', to: "index#about"
  get '/', to: "index#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  #include UsersValidator
  before_save :encrypt_password
  after_save :clear_password
  #attr_accessor :password

  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..100 }
  validates :email, :presence => true, :uniqueness => true
  validates_email_format_of :email, :message => 'Please enter a valid email'
  #validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_length_of :password, :in => 6..100, :on => :create
  validates_with UsersValidator

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.password= BCrypt::Engine.hash_secret(password, salt)
    end
  end
  def clear_password
    self.password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @user = User.new
  end

  def login
    if request.post?
      respond_to do |format|
        @user = User.find_by(username: login_params[:username])
        if(@user.nil?)
          @error = "Invalid Username or password"
          format.html { render :login }
          format.json { render json: {notice: 'Invalid Username or password.'}, status: :unprocessable_entity }
        else
          hashed_pass = BCrypt::Engine.hash_secret(login_params[:password], @user.salt)
          if(hashed_pass!=@user.password)
            @error = "Invalid Username or password"
            format.html { render :login }
            format.json { render json: {notice: 'Invalid Username or password.'}, status: :unprocessable_entity }
          else
            session[:user_id] = @user.id
            format.html {redirect_to :index}
            format.html {render json: {success: true}}
          end
        end
      end
    end

    #@user = User.find_by(username: login_params[:username])
  end

  def register
    @user = User.new
    if request.post?
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :register }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def about
  end

  private
    def login_params
      params.permit(:username, :password)
    end
    def user_params
      params.require(:user).permit(:email, :username, :password)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.fetch(:transaction, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  #def index
  #  @users = User.all
  #end

  # GET /users/1
  # GET /users/1.json
  #def show
  #end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  #def edit
  #end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

class UsersValidator < ActiveModel::Validator
  def validate(record)
    if record.email != "paul.d.rodriguez@outlook.com"
      record.errors[:base] << "You are not allowed to make an account"
    end
  end
end

app/views/index/_form_login.html.erb
<%= form_tag({controller: "index", action: "login"}, method: "post",
class: "pure-form pure-form-aligned") do %>
<% if !error.nil? %>
<div id="error_explanation">
  <h2><%= error %></h2>
</div>
<% end %>
<fieldset>
  <div class="pure-control-group">
<%= label_tag(:username, "Username:") %>
 <%= text_field_tag(:username) %>
 </div>
 <div class="pure-control-group">
   <%= label_tag(:password, "Password:") %>
    <%= password_field_tag(:password) %>
 </div>
 <div class="pure-controls">
 <%= button_tag("Search", type: "submit", class: "pure-button pure-button-primary") %>
 </div>
 </fieldset>
<% end %>

app/views/index/_form_new_user.html.erb
<%= form_for user, :url => register_path(user),
html: {class: "pure-form pure-form-aligned"} do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset>
  <div class="pure-control-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="pure-control-group">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="pure-control-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="pure-controls">
    <%= f.submit "Register", class: "pure-button pure-button-primary" %>
  </div>
</fieldset>
<% end %>

app/views/index/login.html.erb
<h1>Login to your account</h1>
<%= render 'form_login', error: @error %>

app/views/index/register.html.erb
<h1>Register a New Account</h1>
<%= render 'form_new_user', user: @user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FatWallet</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'https://unpkg.com/purecss@0.6.2/build/pure-min.css', integrity: "sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD", crossorigin: "anonymous" %>
    <%= stylesheet_link_tag    'application', "https://unpkg.com/purecss@0.6.2/build/grids-responsive-min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render template: "layouts/header" %>
    <section class="content">
      <%= yield %>
    </section>
  </body>
</html>

app/views/layouts/header.html.erb
<header>
<div>Fat Wallet</div>
</header>

<nav class="pure-menu pure-menu-horizontal fw-nav-bar pure-menu-scrollable">
  <div class="open-nav-bar hide-mobile">Open</div>
  <ul class="pure-menu-list">
    <li class="pure-menu-item text-right color-white">
      <div class="close-nav-bar">X</div>
    </li>
    <li class="pure-menu-item">
      <%= link_to "Login", login_path, class: "pure-menu-link" %>
    </li>
    <li class="pure-menu-item">
      <%= link_to "Register", register_path, class: "pure-menu-link" %>
    </li>
    <li class="pure-menu-item">
      <%= link_to "About", about_path, class: "pure-menu-link" %>
    </li>
  </ul>
</nav>

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_area :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>